FROM node:alpine as prepare

ENV NODE_ENV="production"
WORKDIR /usr/app

COPY package.json .
RUN yarn install
COPY . .
RUN yarn web:build

FROM nginx:1.12-alpine
ENV REACT_APP_VERSION="1.1.2."
COPY --from=prepare /usr/app/build /usr/share/nginx/html
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]