FROM node:alpine as prepare

ENV NODE_ENV="production"
ENV REACT_APP_PLATFORM="web"
WORKDIR /usr/app

COPY package.json .
RUN yarn install
COPY . .
RUN yarn web:build

FROM nginx:1.12-alpine
WORKDIR /usr/share/nginx/html
COPY --from=prepare /usr/app/build .
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]