FROM node:8-alpine as build
ENV NODE_ENV="production"
WORKDIR /usr/app
COPY package.docker.build.json ./package.json
RUN yarn install
COPY ./tsconfig.json ./tsconfig.json
COPY ./src ./src
RUN yarn build

FROM node:8-alpine as prod
ENV NODE_ENV="production"
WORKDIR /usr/app
COPY package.docker.prod.json ./package.json
RUN yarn install
COPY ./tsconfig.json ./tsconfig.json

FROM node:8-alpine
ENV NODE_ENV="production"
WORKDIR /usr/app
COPY --from=prod /usr/app/node_modules /usr/app/node_modules
COPY --from=prod /usr/app/package.json /usr/app/package.json
COPY --from=build /usr/app/build /usr/app/src
EXPOSE 4000

CMD ["yarn", "start"]