import {MigrationInterface, QueryRunner} from "typeorm";

export class ResponsibleForTs1580279991640 implements MigrationInterface {
    name = 'ResponsibleForTs1580279991640'

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "temporary_ts" ("id" varchar PRIMARY KEY NOT NULL, "number" varchar NOT NULL, "receiptYear" varchar NOT NULL, "commissioningYear" varchar, "decommissionYear" varchar, "isBroken" boolean NOT NULL DEFAULT (0), "unitId" varchar, "infoTypeId" varchar, "tsTypeId" varchar, "tableId" varchar, "tableItemId" varchar, "tsPurposeId" varchar, "responsible" varchar, "comment" varchar, CONSTRAINT "UQ_d4f7facf08e027efc179073c08b" UNIQUE ("number"), CONSTRAINT "UQ_c12ba576091bbf833e549932917" UNIQUE ("responsible"), CONSTRAINT "FK_36222a86d139d6dc9cb6711978c" FOREIGN KEY ("tsPurposeId") REFERENCES "ts_purpose" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_427927c64c9d85c35209fa28afc" FOREIGN KEY ("tableItemId") REFERENCES "table_item" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_79e77b1f5c9e0db84cd5885c02e" FOREIGN KEY ("tableId") REFERENCES "table" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a724320c77ffd6bb6f85f5851b0" FOREIGN KEY ("tsTypeId") REFERENCES "ts_type" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_45e048d96af76a22aa816335a34" FOREIGN KEY ("infoTypeId") REFERENCES "info_type" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_71334c42fa85127ace7f6d7e134" FOREIGN KEY ("unitId") REFERENCES "unit" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_ts"("id", "number", "receiptYear", "commissioningYear", "decommissionYear", "isBroken", "unitId", "infoTypeId", "tsTypeId", "tableId", "tableItemId", "tsPurposeId", "responsible", "comment") SELECT "id", "number", "receiptYear", "commissioningYear", "decommissionYear", "isBroken", "unitId", "infoTypeId", "tsTypeId", "tableId", "tableItemId", "tsPurposeId", "responsible", "comment" FROM "ts"`, undefined);
        await queryRunner.query(`DROP TABLE "ts"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_ts" RENAME TO "ts"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_ts" ("id" varchar PRIMARY KEY NOT NULL, "number" varchar NOT NULL, "receiptYear" varchar NOT NULL, "commissioningYear" varchar, "decommissionYear" varchar, "isBroken" boolean NOT NULL DEFAULT (0), "unitId" varchar, "infoTypeId" varchar, "tsTypeId" varchar, "tableId" varchar, "tableItemId" varchar, "tsPurposeId" varchar, "responsible" varchar, "comment" varchar, CONSTRAINT "UQ_d4f7facf08e027efc179073c08b" UNIQUE ("number"), CONSTRAINT "UQ_c12ba576091bbf833e549932917" UNIQUE ("responsible"), CONSTRAINT "FK_36222a86d139d6dc9cb6711978c" FOREIGN KEY ("tsPurposeId") REFERENCES "ts_purpose" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_427927c64c9d85c35209fa28afc" FOREIGN KEY ("tableItemId") REFERENCES "table_item" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_79e77b1f5c9e0db84cd5885c02e" FOREIGN KEY ("tableId") REFERENCES "table" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a724320c77ffd6bb6f85f5851b0" FOREIGN KEY ("tsTypeId") REFERENCES "ts_type" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_45e048d96af76a22aa816335a34" FOREIGN KEY ("infoTypeId") REFERENCES "info_type" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_71334c42fa85127ace7f6d7e134" FOREIGN KEY ("unitId") REFERENCES "unit" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_ts"("id", "number", "receiptYear", "commissioningYear", "decommissionYear", "isBroken", "unitId", "infoTypeId", "tsTypeId", "tableId", "tableItemId", "tsPurposeId", "responsible", "comment") SELECT "id", "number", "receiptYear", "commissioningYear", "decommissionYear", "isBroken", "unitId", "infoTypeId", "tsTypeId", "tableId", "tableItemId", "tsPurposeId", "responsible", "comment" FROM "ts"`, undefined);
        await queryRunner.query(`DROP TABLE "ts"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_ts" RENAME TO "ts"`, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "ts" RENAME TO "temporary_ts"`, undefined);
        await queryRunner.query(`CREATE TABLE "ts" ("id" varchar PRIMARY KEY NOT NULL, "number" varchar NOT NULL, "receiptYear" varchar NOT NULL, "commissioningYear" varchar, "decommissionYear" varchar, "isBroken" boolean NOT NULL DEFAULT (0), "unitId" varchar, "infoTypeId" varchar, "tsTypeId" varchar, "tableId" varchar, "tableItemId" varchar, "tsPurposeId" varchar, "responsible" varchar, "comment" varchar, CONSTRAINT "UQ_d4f7facf08e027efc179073c08b" UNIQUE ("number"), CONSTRAINT "UQ_c12ba576091bbf833e549932917" UNIQUE ("responsible"), CONSTRAINT "FK_36222a86d139d6dc9cb6711978c" FOREIGN KEY ("tsPurposeId") REFERENCES "ts_purpose" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_427927c64c9d85c35209fa28afc" FOREIGN KEY ("tableItemId") REFERENCES "table_item" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_79e77b1f5c9e0db84cd5885c02e" FOREIGN KEY ("tableId") REFERENCES "table" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a724320c77ffd6bb6f85f5851b0" FOREIGN KEY ("tsTypeId") REFERENCES "ts_type" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_45e048d96af76a22aa816335a34" FOREIGN KEY ("infoTypeId") REFERENCES "info_type" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_71334c42fa85127ace7f6d7e134" FOREIGN KEY ("unitId") REFERENCES "unit" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "ts"("id", "number", "receiptYear", "commissioningYear", "decommissionYear", "isBroken", "unitId", "infoTypeId", "tsTypeId", "tableId", "tableItemId", "tsPurposeId", "responsible", "comment") SELECT "id", "number", "receiptYear", "commissioningYear", "decommissionYear", "isBroken", "unitId", "infoTypeId", "tsTypeId", "tableId", "tableItemId", "tsPurposeId", "responsible", "comment" FROM "temporary_ts"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_ts"`, undefined);
        await queryRunner.query(`ALTER TABLE "ts" RENAME TO "temporary_ts"`, undefined);
        await queryRunner.query(`CREATE TABLE "ts" ("id" varchar PRIMARY KEY NOT NULL, "number" varchar NOT NULL, "receiptYear" varchar NOT NULL, "commissioningYear" varchar, "decommissionYear" varchar, "isBroken" boolean NOT NULL DEFAULT (0), "unitId" varchar, "infoTypeId" varchar, "tsTypeId" varchar, "tableId" varchar, "tableItemId" varchar, "tsPurposeId" varchar, "responsible" varchar, "comment" varchar, CONSTRAINT "UQ_d4f7facf08e027efc179073c08b" UNIQUE ("number"), CONSTRAINT "UQ_c12ba576091bbf833e549932917" UNIQUE ("responsible"), CONSTRAINT "FK_36222a86d139d6dc9cb6711978c" FOREIGN KEY ("tsPurposeId") REFERENCES "ts_purpose" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_427927c64c9d85c35209fa28afc" FOREIGN KEY ("tableItemId") REFERENCES "table_item" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_79e77b1f5c9e0db84cd5885c02e" FOREIGN KEY ("tableId") REFERENCES "table" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a724320c77ffd6bb6f85f5851b0" FOREIGN KEY ("tsTypeId") REFERENCES "ts_type" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_45e048d96af76a22aa816335a34" FOREIGN KEY ("infoTypeId") REFERENCES "info_type" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_71334c42fa85127ace7f6d7e134" FOREIGN KEY ("unitId") REFERENCES "unit" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "ts"("id", "number", "receiptYear", "commissioningYear", "decommissionYear", "isBroken", "unitId", "infoTypeId", "tsTypeId", "tableId", "tableItemId", "tsPurposeId", "responsible", "comment") SELECT "id", "number", "receiptYear", "commissioningYear", "decommissionYear", "isBroken", "unitId", "infoTypeId", "tsTypeId", "tableId", "tableItemId", "tsPurposeId", "responsible", "comment" FROM "temporary_ts"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_ts"`, undefined);
    }

}
