version: '3'

services:
  phoenix-backend:
    image: phoenix-backend:latest
    ports:
    - "4000:4000"
    environment:
      ACCESS_SECRET: ${ACCESS_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      GRAPHQL_ENDPOINT: ${GRAPHQL_ENDPOINT}
      GRAPHQL_HOST: 0.0.0.0
      GRAPHQL_PORT: ${GRAPHQL_PORT}
    restart: always
    volumes:
    - .:/usr/app/src/data:z

  phoenix-frontend:
    depends_on:
    - phoenix-backend
    image: phoenix-frontend:latest
    ports:
    - "80:80"
    restart: no